var mouseEvent = "empty"
document.getElementById("myCanvas");
ctx = myCanvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = "red";
ctx.linewidth = 1;
ctx.rect(150,143,430,200)
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "blue";
ctx.linewidth = 10;
ctx.arc(250,210,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "yellow";
ctx.linewidth = 10;
ctx.arc(290,250,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "black";
ctx.linewidth = 10;
ctx.arc(340,210,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "green";
ctx.linewidth = 10;
ctx.arc(390,250,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "red";
ctx.linewidth = 10;
ctx.arc(430,210,40,0,2*Math.PI);
ctx.stroke();